# Learn Python - NumPy

1. [Basic Arrays](#basic-arrays)
2. [Basic NumPy Example](#basic-numpy-example)
3. [NumPy Array Attributes](#numpy-array-attributes)
4. [Array Creation](#array-creation)
5. [Sort](#sort)
6. [Concatenate](#concatenate)
7. [Reshape](#reshape)
8. [Array Arithmetic](#array-arithmetic)
9. [Mathematical Functions](#mathematical-functions)

## NumPy Basics

### Basic arrays

In [32]:
# Basic array
arr = [1, 2, 3, 4, 5]
print(f"Basic array: {arr}, Type: {type(arr)}")

# Basic Numpy array
import numpy as np 
np_arr = np.array([1, 2, 3, 4, 5]) # Array dimension 1
print(f"Basic array: {np_arr}, Type: {type(np_arr)}")

np_arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # Array dimension 2
print("Basic 2D Numpy array:\n", np_arr2d)

print(np_arr[0])  # Access first element
print(np_arr2d[1, 2])  # Access element at row 1, column 2

np_arr[0] = 10  # Modify first element
print("Modified Numpy array:", np_arr)

np_arr01 = np_arr[1:3]
print("Sliced array: ", np_arr01)



Basic array: [1, 2, 3, 4, 5], Type: <class 'list'>
Basic array: [1 2 3 4 5], Type: <class 'numpy.ndarray'>
Basic 2D Numpy array:
 [[1 2 3]
 [4 5 6]]
1
6
Modified Numpy array: [10  2  3  4  5]
Sliced array:  [2 3]


### Basic numpy example

In [33]:
# Program to demonstrate 1D array operations

import numpy as np # Importing the numpy library
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
c = a + b # Element-wise addition of two arrays

print("Sum of a and b:", c)

a.shape # Getting the shape of array a

Sum of a and b: [5 7 9]


(3,)

### NumPy array attributes

In [34]:
a = np.array([1, 2, 3]) 
print("Array a:", a)

print("ndim: " + str(a.ndim)) # Number of dimensions
print("shape: " + str(a.shape)) # Shape of the array
print("size: " + str(a.size))  # Total number of elements
print("dtype: " + str(a.dtype)) # Data type of elements
print("itemsize: " + str(a.itemsize)) # Size of each element in bytes
print("nbytes: " + str(a.nbytes))  # Total size of the array in bytes
print("tolist: " + str(a.tolist())) # Convert array to list


Array a: [1 2 3]
ndim: 1
shape: (3,)
size: 3
dtype: int64
itemsize: 8
nbytes: 24
tolist: [1, 2, 3]


### Array creation

In [35]:
arr = np.zeros(5) # Create an array of zeros with 5 elements
print(arr)

arr = np.ones((2, 3)) # Create a 2x3 array of 1's
print(arr)

arr = np.arange(0, 10) # Create an array with values from 0 to 9
print(arr)

arr = np.arange(0, 10, 2) # Create an array with values from 0 to 9 with step 2
print(arr)

arr = np.linspace(0, 1, 5) # Create an array of 5 values evenly spaced between 0 and 1
print(arr)

arr = np.random.rand(3, 2) # Create a 3x2 array with random values between 0 and 1
print(arr)

arr = np.empty((3, 3)) # Create an uninitialized 3x3 array
print(arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.608743   0.05584051]
 [0.19985612 0.47817111]
 [0.01762561 0.57386535]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Sort

In [36]:
arr = np.array([3, 1, 2, 43, 64, 2])
print(arr)

sorted_arr = np.sort(arr) # Sort the array
print("Sorted array:", sorted_arr)

[ 3  1  2 43 64  2]
Sorted array: [ 1  2  2  3 43 64]


### Concatenate

In [37]:
# Concatenation of arrays

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.concatenate((a,b)) # Concatenate two arrays along existing axis
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print ("Current Shapre:", arr.shape)
reshaped_arr = arr.reshape((3, 2)) # Reshape the array to 3 rows and 2 columns
print(reshaped_arr)
print ("Current Shapre:", reshaped_arr.shape)

Current Shapre: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Current Shapre: (3, 2)


### Array arithematics

In [39]:
# Array Addition

np_a = np.array([1, 2, 3, 4, 5])
np_b = np.array([11, 12, 13, 14, 15])
c = np_a + np_b # Element-wise addition
print("Array after addition:", c)

# Array Multiplication
c = np_a * np_b # Element-wise multiplication
print("Array after multiplication:", c)
np.multiply(np_a, np_b) # Using numpy multiply function
print("Array after multiplication using np.multiply():", c)

# Array Division
c = np_a / np_b # Element-wise division
print("Array after division:", c)

d = np.divide(np_a, np_b) # Using numpy divide function
print("Array after division using np.divide():", d)

# Dot product
c = np.dot(np_a, np_b) # Dot product of two arrays
print("Dot product of a and b:", c)

Array after addition: [12 14 16 18 20]
Array after multiplication: [11 24 39 56 75]
Array after multiplication using np.multiply(): [11 24 39 56 75]
Array after division: [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
Array after division using np.divide(): [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
Dot product of a and b: 205


### Mathematical functions

In [40]:
print("Pi :", np.pi) # Print the value of Pi
print("np.sin(1):", np.sin(1)) # Sign function for positive number
print("np.cos(-5):", np.cos(-5)) # Sign function for negative number
print("np.linespace(0, 1, 5):", np.linspace(0, 1, 5)) # Generate 5 evenly spaced numbers between 0 and 1





Pi : 3.141592653589793
np.sin(1): 0.8414709848078965
np.cos(-5): 0.28366218546322625
np.linespace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
