WORK IN PROGRESS
Please visit later

## NumPy Basics

### Basic arrays

In [9]:
# Basic array
arr = [1, 2, 3, 4, 5]
print("Basic array:", arr)

# Basic Numpy array
import numpy as np 
np_arr = np.array([1, 2, 3, 4, 5]) # Array dimension 1
print("Basic Numpy array:", np_arr)

np_arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # Array dimension 2
print("Basic 2D Numpy array:\n", np_arr2d)

print(np_arr[0])  # Access first element
print(np_arr2d[1, 2])  # Access element at row 1, column 2

np_arr[0] = 10  # Modify first element
print("Modified Numpy array:", np_arr)


Basic array: [1, 2, 3, 4, 5]
Basic Numpy array: [1 2 3 4 5]
Basic 2D Numpy array:
 [[1 2 3]
 [4 5 6]]
1
6
Modified Numpy array: [10  2  3  4  5]


### Basic numpy example

In [ ]:
# Program to demonstrate 1D array operations

import numpy as np # Importing the numpy library
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
c = a + b # Element-wise addition of two arrays

print("Sum of a and b:", c)

a.shape # Getting the shape of array a

Sum of a and b: [5 7 9]


(3,)

### NumPy array attributes

In [15]:
a = np.array([1, 2, 3]) 
print("Array a:", a)

print("ndim: " + str(a.ndim)) # Number of dimensions
print("shape: " + str(a.shape)) # Shape of the array
print("size: " + str(a.size))  # Total number of elements
print("dtype: " + str(a.dtype)) # Data type of elements
print("itemsize: " + str(a.itemsize)) # Size of each element in bytes
print("nbytes: " + str(a.nbytes))  # Total size of the array in bytes
print("tolist: " + str(a.tolist())) # Convert array to list


Array a: [1 2 3]
ndim: 1
shape: (3,)
size: 3
dtype: int64
itemsize: 8
nbytes: 24
tolist: [1, 2, 3]


### Array creation

In [36]:
arr = np.zeros(5) # Create an array of zeros with 5 elements
print(arr)

arr = np.ones((2, 3)) # Create a 2x3 array of 1's
print(arr)

arr = np.arange(0, 10) # Create an array with values from 0 to 9
print(arr)

arr = np.arange(0, 10, 2) # Create an array with values from 0 to 9 with step 2
print(arr)

arr = np.linspace(0, 1, 5) # Create an array of 5 values evenly spaced between 0 and 1
print(arr)

arr = np.random.rand(3, 2) # Create a 3x2 array with random values between 0 and 1
print(arr)

arr = np.empty((3, 3)) # Create an uninitialized 3x3 array
print(arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.40401962 0.0584562 ]
 [0.12892242 0.84282722]
 [0.52393118 0.70694083]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Sort

In [41]:
arr = np.array([3, 1, 2, 43, 64, 2])
print(arr)

sorted_arr = np.sort(arr) # Sort the array
print("Sorted array:", sorted_arr)

[ 3  1  2 43 64  2]
Sorted array: [ 1  2  2  3 43 64]


### Concatenate

In [ ]:
# Concatenation of arrays

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.concatenate((a,b)) # Concatenate two arrays along existing axis
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print ("Current Shapre:", arr.shape)
reshaped_arr = arr.reshape((3, 2)) # Reshape the array to 3 rows and 2 columns
print(reshaped_arr)
print ("Current Shapre:", reshaped_arr.shape)

Current Shapre: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Current Shapre: (3, 2)
